name: Go package
on: [push]
env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  GITHUB_USER: nayuta-ai
  TARGET_REPOSITORY: k8s-argo
  GITHUB_BRANCH: update_tag
  TEST_VARIABLE: test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install Lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Lint
        run: golangci-lint run

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...